---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/starkandwayne/concourse-tutorial.git
      branch: develop

  - name: resource-app
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

  - name: resource-tanzu
    type: git
    source:
      uri: https://github.com/circlechange/tanzu_demo.git


jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-tutorial
      - get: resource-app
        trigger: true
      - get: resource-tanzu
        trigger: true
      - task: web-app-tests
        file: resource-tutorial/tutorials/basic/job-inputs/task_run_tests.yml
      - task: deploy-app
        file: resource-tanzu/pipeline/deploy_app_task.yml

  - name: job-deploy-app
    public: true
    plan:
    - get: resource-tutorial
    - get: resource-app
      passed: [job-test-app]
    - get: resource-tanzu
    - task: deploy-app
      file: resource-tanzu/pipeline/deploy_app_task.yml
