---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/starkandwayne/concourse-tutorial.git
      branch: develop

  - name: resource-app
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

  - name: work-image
    type: registry-image
    source:
      repository: golang
      tag: 1.9-alpine

  - name: resource-tanzu
    type: git
    source:
      uri: https://github.com/circlechange/tanzu_demo.git


jobs:
  - name: job-create-cluster
    public: true
    plan:
      - get: resource-tutorial
      - get: resource-app
      - get: resource-tanzu
      - get: work-image
        trigger: true
      - task: web-app-tests
        file: resource-tutorial/tutorials/basic/job-inputs/task_run_tests.yml
      - task: create-cluster
        file: resource-tanzu/pipeline_create_cluster_test/create_cluster_task.yml
        image: work-image

  - name: job-deploy-monitor
    public: true
    plan:
    - get: resource-tutorial
    - get: resource-app
    - get: work-image
      passed:
      - job-create-cluster
    - get: resource-tanzu
      passed: [job-create-cluster]
      trigger: true
    - task: deploy-monitor
      file: resource-tanzu/pipeline_create_cluster_test/create_cluster_task.yml
      image: work-image

  - name: job-deploy-logs
    public: true
    plan:
    - get: resource-tutorial
    - get: resource-app
    - get: work-image
      passed:
      - job-deploy-monitor
    - get: resource-tanzu
      passed:
      - job-deploy-monitor
      trigger: true
    - task: deploy-logs
      file: resource-tanzu/pipeline_create_cluster_test/create_cluster_task.yml
      image: work-image

  - name: job-deploy-velero
    public: true
    plan:
    - get: resource-tutorial
    - get: resource-app
    - get: work-image
      passed:
      - job-deploy-logs 
    - get: resource-tanzu
      passed:
      - job-deploy-logs
      trigger: true
    - task: deploy-velero
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang, tag: 1.9-alpine}
        inputs:
        - name: resource-tanzu
        run:
          path: resource-tanzu/pipeline_create_cluster/create_cluster_task.sh

